implemented update handler. refactored service return type for save a…
jarri-abidi/todolist pull request #10
Opened 2022-10-17 06:03 UTC by markhaur

implemented update handler. refactored service return type for save and update method. refactored erroneous test cases

2022-10-17 06:07 UTC, jarri-abidi commented on checklist/http.go
> +			writeError(w, err)
we should return here

2022-10-17 06:07 UTC, markhaur commented on checklist/http.go
> +			writeError(w, err)
lemme do it

2022-10-17 06:09 UTC, jarri-abidi commented on checklist/service.go
> +	}
would it make sense to have 1 repository method like Upsert? I mean to save multiple db calls

2022-10-17 06:10 UTC, markhaur commented on checklist/service.go
> +	}
Lemme think about it till tomorrow.

2022-10-17 06:11 UTC, jarri-abidi requested changes
Need to return 201 if newly created

2022-10-24 03:27 UTC, jarri-abidi approved these changes

2022-10-24 03:28 UTC, merged